spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/test_database
    username: postgres
    password: DrCarmen1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        auto-startup: false
server:
  error:
    include-message: always

rabbit-mq:
  config:
    username: "guest"
    password: "guest"
    virtualHost: "/"
    hostname: "localhost"
    port: 5672
  listener-containers-delay: 5000
  order-properties:
    queue: PurchasedProductQueue
    dead-letter-queue: PurchasedProductQueueDeadLetter
    exchange: OrderExchange
    dead-letter-exchange: OrderExchangeDeadLetter
    routing-key: order.product.purchase
    dead-letter-routing-key: order.product.purchase.dl